// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        string                `json:"id"`
	EventType string                `json:"event_type"`
	ItemID    sql.NullString        `json:"item_id"`
	UserID    string                `json:"user_id"`
	Payload   pqtype.NullRawMessage `json:"payload"`
	Source    string                `json:"source"`
	CreatedAt time.Time             `json:"created_at"`
}
