// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetAuditRecordByID(ctx context.Context, id string) (GetAuditRecordByIDRow, error)
	InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) error
	ListAuditRecords(ctx context.Context, limit int32) ([]ListAuditRecordsRow, error)
	ListAuditRecordsByEventType(ctx context.Context, arg ListAuditRecordsByEventTypeParams) ([]ListAuditRecordsByEventTypeRow, error)
	ListAuditRecordsByUserID(ctx context.Context, arg ListAuditRecordsByUserIDParams) ([]ListAuditRecordsByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
