// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type TodoItem struct {
	ID          uuid.UUID    `json:"id"`
	ListID      uuid.UUID    `json:"list_id"`
	Text        string       `json:"text"`
	Completed   bool         `json:"completed"`
	CreatedAt   time.Time    `json:"created_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

type TodoList struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
