// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteTodoItem(ctx context.Context, id uuid.UUID) error
	DeleteTodoItemsByListID(ctx context.Context, listID uuid.UUID) error
	DeleteTodoList(ctx context.Context, id uuid.UUID) error
	GetTodoItemsByListID(ctx context.Context, listID uuid.UUID) ([]TodoItem, error)
	GetTodoListByUserID(ctx context.Context, userID uuid.UUID) (TodoList, error)
	InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) error
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error
	UpsertTodoList(ctx context.Context, arg UpsertTodoListParams) error
}

var _ Querier = (*Queries)(nil)
